---
- name: Install Apache and upload Web page
  hosts: all 
  become: yes

  #объявляем переменные
  vars:
    source_file: ./TestWebSite/
    destin_file:  /var/www/html/

  tasks:
  - name: Install Apache server
    apt: name=apache2 state=latest 

  - name: Copy Web page
    copy: src={{ source_file }} dest={{ destin_file }} mode=0555
    notify: Restart Apache

  - name: Start Apache and enabled
    service: name=apache2 state=started enabled=yes

  #будет вызываться только в том случае, если файлы source_file изменились
  handlers:
  - name: Restart Apache
    service: name=apache2 state=restarted
